spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/kafka
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    open-in-view: false
  kafka:
    bootstrap-servers:
      - 192.168.16.43:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#kafka:
#  server: 192.168.16.43:9092
#  topic: payment
#  group-id: payment-group
#  key:
#    serializer: org.apache.kafka.common.serialization.StringSerializer
#    deserializer: org.apache.kafka.common.serialization.StringSerializer
#  value:
#    serializer: org.apache.kafka.common.serialization.StringSerializer
#    deserializer: org.apache.kafka.common.serialization.StringSerializer
